be_happy_sylius_rights_management:
    rights:
        product:
            list:
                name: 'be_happy_rights_management.rights.product.read'
                route: 'sylius_admin_product_index'
            update:
                name: 'be_happy_rights_management.rights.product.update'
                route: 'sylius_admin_product_update'
            delete:
                name: 'be_happy_rights_management.rights.product.delete'
                route: 'sylius_admin_product_delete'

        right_management:
            index:
                name: 'be_happy_rights_management.rights.admin_group_right_management.index'
                route: 'be_happy_rights_management_admin_group_index'

        taxon:
            create:
                name: 'be_happy_rights_management.rights.taxon.create'
                route: 'sylius_admin_taxon_create'

        inventory:
            index:
                name: 'be_happy_rights_management.rights.inventory.index'
                route: 'sylius_admin_inventory_index'

        product_attribute:
            index:
                name: 'be_happy_rights_management.rights.product_attribute.index'
                route: 'sylius_admin_product_attribute_index'
            create:
                name: 'be_happy_rights_management.rights.product_attribute.create'
                route: 'sylius_admin_product_attribute_create'
            update:
                name: 'be_happy_rights_management.rights.product_attribute.update'
                route: 'sylius_admin_product_attribute_update'

        product_option:
            index:
                name: 'be_happy_rights_management.rights.product_option.index'
                route: 'sylius_admin_product_option_index'
            update:
                name: 'be_happy_rights_management.rights.product_option.update'
                route: 'sylius_admin_product_option_update'
            create:
                name: 'be_happy_rights_management.rights.product_option.create'
                route: 'sylius_admin_product_option_create'

        product_association_type:
            index:
                name: 'be_happy_rights_management.rights.product_association_type.index'
                route: 'sylius_admin_product_association_type_index'
            update:
                name: 'be_happy_rights_management.rights.product_association_type.update'
                route: 'sylius_admin_product_association_type_update'
            create:
                name: 'be_happy_rights_management.rights.product_association_type.create'
                route: 'sylius_admin_product_association_type_create'

        order:
            index:
                name: 'be_happy_rights_management.rights.order.index'
                route: 'sylius_admin_order_index'
            update:
                name: 'be_happy_rights_management.rights.order.update'
                route: 'sylius_admin_order_update'

        customer:
            index:
                name: 'be_happy_rights_management.rights.customer.index'
                route: 'sylius_admin_customer_index'
            update:
                name: 'be_happy_rights_management.rights.customer.update'
                route: 'sylius_admin_customer_update'
            create:
                name: 'be_happy_rights_management.rights.customer.create'
                route: 'sylius_admin_customer_create'
            order_index:
                name: 'be_happy_rights_management.rights.customer.order_index'
                route: 'sylius_admin_customer_order_index'

        customer_group:
            index:
                name: 'be_happy_rights_management.rights.customer_group.index'
                route: 'sylius_admin_customer_group_index'
            create:
                name: 'be_happy_rights_management.rights.customer_group.create'
                route: 'sylius_admin_customer_group_create'
            update:
                name: 'be_happy_rights_management.rights.customer_group.update'
                route: 'sylius_admin_customer_group_update'

        promotion:
            index:
                name: 'be_happy_rights_management.rights.promotion.index'
                route: 'sylius_admin_promotion_index'
            create:
                name: 'be_happy_rights_management.rights.promotion.create'
                route: 'sylius_admin_promotion_create'
            update:
                name: 'be_happy_rights_management.rights.promotion.update'
                route: 'sylius_admin_promotion_update'

        product_review:
            index:
                name: 'be_happy_rights_management.rights.product_review.index'
                route: 'sylius_admin_product_review_index'
            update:
                name: 'be_happy_rights_management.rights.product_review.update'
                route: 'sylius_admin_product_review_update'

        channel:
            index:
                name: 'be_happy_rights_management.rights.channel.index'
                route: 'sylius_admin_channel_index'
            create:
                name: 'be_happy_rights_management.rights.channel.create'
                route: 'sylius_admin_channel_create'
            update:
                name: 'be_happy_rights_management.rights.channel.update'
                route: 'sylius_admin_channel_update'

        country:
            index:
                name: 'be_happy_rights_management.rights.country.index'
                route: 'sylius_admin_country_index'
            create:
                name: 'be_happy_rights_management.rights.country.create'
                route: 'sylius_admin_country_create'
            update:
                name: 'be_happy_rights_management.rights.country.update'
                route: 'sylius_admin_country_update'

        zone:
            index:
                name: 'be_happy_rights_management.rights.zone.index'
                route: 'sylius_admin_zone_index'
            create:
                name: 'be_happy_rights_management.rights.zone.create'
                route: 'sylius_admin_zone_create'
            update:
                name: 'be_happy_rights_management.rights.zone.update'
                route: 'sylius_admin_zone_update'

        currency:
            index:
                name: 'be_happy_rights_management.rights.currency.index'
                route: 'sylius_admin_currency_index'
            create:
                name: 'be_happy_rights_management.rights.currency.create'
                route: 'sylius_admin_currency_create'
            update:
                name: 'be_happy_rights_management.rights.currency.update'
                route: 'sylius_admin_currency_update'

        exchange_rate:
            index:
                name: 'be_happy_rights_management.rights.exchange_rate.index'
                route: 'sylius_admin_exchange_rate_index'
            create:
                name: 'be_happy_rights_management.rights.exchange_rate.update'
                route: 'sylius_admin_exchange_rate_create'
            update:
                name: 'be_happy_rights_management.rights.exchange_rate.index'
                route: 'sylius_admin_exchange_rate_update'

        locale:
            index:
                name: 'be_happy_rights_management.rights.locale.index'
                route: 'sylius_admin_locale_index'
            create:
                name: 'be_happy_rights_management.rights.locale.create'
                route: 'sylius_admin_locale_create'

        payment_method:
            index:
                name: 'be_happy_rights_management.rights.payment_method.index'
                route: 'sylius_admin_payment_method_index'
            create:
                name: 'be_happy_rights_management.rights.payment_method.create'
                route: 'sylius_admin_payment_method_create'
            update:
                name: 'be_happy_rights_management.rights.payment_method.update'
                route: 'sylius_admin_payment_method_update'

        shipping_method:
            index:
                name: 'be_happy_rights_management.rights.shipping_method.index'
                route: 'sylius_admin_shipping_method_index'
            create:
                name: 'be_happy_rights_management.rights.shipping_method.create'
                route: 'sylius_admin_shipping_method_create'
            update:
                name: 'be_happy_rights_management.rights.shipping_method.update'
                route: 'sylius_admin_shipping_method_update'

        shipping_category:
            index:
                name: 'be_happy_rights_management.rights.shipping_category.index'
                route: 'sylius_admin_shipping_category_index'
            create:
                name: 'be_happy_rights_management.rights.shipping_category.create'
                route: 'sylius_admin_shipping_category_create'
            update:
                name: 'be_happy_rights_management.rights.shipping_category.update'
                route: 'sylius_admin_shipping_category_update'

        tax_category:
            index:
                name: 'be_happy_rights_management.rights.tax_category.index'
                route: 'sylius_admin_tax_category_index'
            create:
                name: 'be_happy_rights_management.rights.tax_category.create'
                route: 'sylius_admin_tax_category_create'
            update:
                name: 'be_happy_rights_management.rights.tax_category.update'
                route: 'sylius_admin_tax_category_update'

        tax_rate:
            index:
                name: 'be_happy_rights_management.rights.tax_rate.index'
                route: 'sylius_admin_tax_rate_index'
            create:
                name: 'be_happy_rights_management.rights.tax_rate.create'
                route: 'sylius_admin_tax_rate_create'
            update:
                name: 'be_happy_rights_management.rights.tax_rate.update'
                route: 'sylius_admin_tax_rate_update'

        user:
            index:
                name: 'be_happy_rights_management.rights.admin_user.index'
                route: 'sylius_admin_admin_user_index'
            create:
                name: 'be_happy_rights_management.rights.admin_user.create'
                route: 'sylius_admin_admin_user_create'
            update:
                name: 'be_happy_rights_management.rights.admin_user.update'
                route: 'sylius_admin_admin_user_update'

        company_data:
            index:
                name: 'be_happy_rights_management.rights.company_data.index'
                route: 'sylius_admin_company_data_index'
