imports:
    - { resource: '@BeHappySyliusRightsManagementPlugin/Resources/config/services.yaml' }
    - { resource: '@BeHappySyliusRightsManagementPlugin/Resources/config/resources.yaml' }
    - { resource: '@BeHappySyliusRightsManagementPlugin/Resources/config/grids.yaml' }
    - { resource: '@BeHappySyliusRightsManagementPlugin/Resources/config/right_management.yaml' }
